import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import globals from 'globals';

export default [
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 12,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2021,
        // Foundry VTT globals
        foundry: 'readonly',
        game: 'readonly',
        ui: 'readonly',
        canvas: 'readonly',
        CONFIG: 'readonly',
        Hooks: 'readonly',
        Actors: 'readonly',
        Items: 'readonly',
        Scenes: 'readonly',
        Combats: 'readonly',
        Macros: 'readonly',
        Messages: 'readonly',
        Playlists: 'readonly',
        Users: 'readonly',
        Folders: 'readonly',
        Roll: 'readonly',
        Dialog: 'readonly',
        ChatMessage: 'readonly',
        Actor: 'readonly',
        Item: 'readonly',
        Scene: 'readonly',
        Combat: 'readonly',
        Macro: 'readonly',
        Playlist: 'readonly',
        User: 'readonly',
        Folder: 'readonly',
        Application: 'readonly',
        FormApplication: 'readonly',
        ActorSheet: 'readonly',
        ItemSheet: 'readonly',
        DocumentSheet: 'readonly',
        ActiveEffect: 'readonly',
        ActiveEffectConfig: 'readonly',
        Handlebars: 'readonly',
        renderTemplate: 'readonly',
        loadTemplates: 'readonly',
        TextEditor: 'readonly',
        FilePicker: 'readonly',
        mergeObject: 'readonly',
        duplicate: 'readonly',
        isObjectEmpty: 'readonly',
        diffObject: 'readonly',
        expandObject: 'readonly',
        flattenObject: 'readonly',
        getProperty: 'readonly',
        setProperty: 'readonly',
        hasProperty: 'readonly',
        randomID: 'readonly',
        CONST: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
      },
    },
    plugins: {
      prettier: prettierPlugin,
    },
    rules: {
      'no-invalid-this': 0,
      'camelcase': 0,
      'prettier/prettier': [
        'error',
        {
          endOfLine: 'auto',
        },
      ],
    },
  },
];
