services:
  foundryvttdev:
    image: andrea/fvtt-docker:latest
    container_name: fvtt12-dev
    ports: 
      - 24001:30000
    volumes:
      - C:\foundry-dev\Data:/data/foundryvtt
      - C:\Users\Coccinella\Documents\git\foundry-dod:/data/foundryvtt/Data/systems/dod
      - C:\foundry-dev:/host
      - C:\foundry-dev\App:/opt/foundryvtt/resources/app
    restart: unless-stopped
